server:
  port: 8080
  servlet:
    context-path: /comma-film

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comma
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: true
        highlight_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE