server:
  port: 8090
  servlet:
    context-path: /comma-film

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comma
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: true
        highlight_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# 로컬 테스트 시 dir, imageUrl을 로컬로 변경해야함. 현재는 dir은 도커의 디렉토리고, url은 DDNS이다.
file:
  dir: /images
#  dir: /Users/sondonghwan/Desktop/images
  imageUrl: http://dh-project.mooo.com:8090/comma-film/image
#  imageUrl: http://localhost:8090/comma-film/image